import { NavMenu } from '../components/nav-menu'
import { ThemeSwitch } from '../components/theme-switch'
import './globals.css'
import styles from './layout.module.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: {
    template: '%s · My Movie Library',
    default: 'My Movie Library',
  },
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${styles.rootLayout} ${inter.className}`}>
        <header>
          <NavMenu />
          <ThemeSwitch />
        </header>

        <main>{children}</main>

        <footer>Powered by React+Next.js</footer>
      </body>
    </html>
  )
}
